### PR TITLE
Coroutine Audioservice

### PR DESCRIPTION
**Pull request by Quillraven**
The idea is to have the audio functionality running in a separate coroutine:
1) the main thread can queue sounds into the service (produce)
2) the audioservice loads the sound, if it is not loaded yet and queues it for playing
3) at the end of a frame the audioservice analyzes the queued sounds and plays them accordingly

Example: assume there are no sounds loaded yet
1) main thread queues explosion sound
2) sound is not loaded yet -> load it
3) main thread queues explosion sound
4) sound was already queued, ignore the request and set the already queued sound volume to the maximum of both
5) end of frame is reached; if explosion was loaded already play it; otherwise no sound will be played

### CODE REVIEW

**Comment by Quillraven** [comment]
@czyzby can you please look over the audio.kt file and give feedback to the `DefaultAudioService` class implementation? The idea is to handle audio related stuff in a coroutine to avoid blocking the main thread when sound/music is loaded.

Currently I only implemented a draft for sound effects. I notice that the first request of a sound is not played because it is not loaded in time (at least that is my assumption). Additional requests are then working fine.

**Comment by czyzby** [comment]
I'm a bit worried about this part:
```kotlin
        KtxAsync.launch {
            if (!assets.isLoaded<Sound>(soundAsset.filePath)) {
                LOG.debug { "Loading new sound asset of type $soundAsset" }
                val sound = assets.loadAsync<Sound>(soundAsset.filePath)
                soundCache.put(soundAsset, sound.await())
            }
        }
```

1. It can use `loadAsync` on the same sound multiple times while it is unloaded. This will work just fine, as `AssetStorage` will simply increase the reference count, but if plan on unloading individual sounds later, you have to remember to do this the same amount of times as they were loaded. (Or just call `AssetStorage.dispose` to unload all assets.)
2. Since you're calling this while requesting to play a sound, you should expect a slight delay or missed sound requests each time you play a sound for the first time, as it will take some time to load them.

You can refactor this slightly by changing `isLoaded` to `contains` (or `in` operator) and putting the check outside of the coroutine, to avoid starting unnecessary coroutines on each sound request.

However, unless you plan on having _a lot_ of sounds, most of which will remain unloaded and it makes sense to load them on demand, I'd start with a simpler approach where you load all of your sounds up front.

As for the manager with `update` - I usually went for immediate `sound.play` calls as far as I can remember, but this could also work.

**Comment by Quillraven** [comment]
@czyzby thanks for the feedback! The simpler approach definitely makes more sense in this small game but I was thinking about a general solution also for big games. I have no idea how they do it but e.g. imagine a MMORPG with hundres of soundeffects and you do not know which ones you need in which area of the game. I thought that an approach like this makes sense.

But, as you already mentioned, might be tricky to implement and complicated with concurrency issues.

Since I want this game to be used for a future libktx video tutorial, I will keep it simple ;)

**Comment by Quillraven** [comment]
> As for the manager with `update` - I usually went for immediate `sound.play` calls as far as I can remember, but this could also work.

The update makes sense in my opinion because imagine you request the same sound multiple times in a frame? The volume will get louder multiple times.
E.g. multiple entities get damaged within one frame and you want to play a damage sound. It should be played only once with the highest requested volume.

**Comment by czyzby** [comment]
Depends on the game, I guess. If you get that many sound requests per frame then it might make sense to group them, but you could consider aggregating sounds even further. Even a single sound on each frame would be a lot.

**Comment by Quillraven** [comment]
@czyzby I would appreciate if you could look over it once more please. I simplified it now to load sounds in the LoadingScreen.

I saw a `getAssetDescriptor` function in AssetStorage but it is not static and therefore I cannot use it in the asset enums. Would it be a good idea to make it static?

**Comment by czyzby** [comment]
> I saw a `getAssetDescriptor` function in AssetStorage but it is not static and therefore I cannot use it in the asset enums. Would it be a good idea to make it static?

It automatically resolves `FileHandle` - that's why it's not static. You can find static alternatives in `ktx-assets` - `ktx-assets` are not only `AssetManager` extensions, there are some utilities around files and disposables as well.

**Comment by czyzby** [comment]
Looks good so far, I'm excited to see the whole game.

One comment though:

```kotlin
LOG.debug { "It took ${timeToLoadAndInit * 0.001f} seconds to load assets and initialize" }
```
I believe this is false, as it won't measure the time it took to complete the coroutine. Anything that happens inside `KtxAsync.launch` will be outside of the measurement.

Currently, it only measures the time of asset scheduling and coroutine launching. You would have to save start time at the beginning of this function and compare it against end time measured at the end of the coroutine or `assetsLoaded` method.

**Comment by Quillraven** [comment]
@czyzby haha what a funny coincident. I just noticed that right now and wanted to contact you but you already wrote that here :)

I did it correctly in Quilly Jumper by measuring the time by storing it with System.currentTimeMillis and doing the System.currentTimeMillis - old calculation myself.

In this project I remembered that there is something OOTB for kotlin and read this [article](https://kotlinlang.org/docs/reference/coroutines/composing-suspending-functions.html) with following snippet:

```kotlin
val time = measureTimeMillis {
    val one = async { doSomethingUsefulOne() }
    val two = async { doSomethingUsefulTwo() }
    println("The answer is ${one.await() + two.await()}")
}
println("Completed in $time ms")
```

So, I thought I can use that but seems like in my case it does not work because KtxAsync has a different CoroutineScope than the show method?

**Comment by Quillraven** [comment]
@czyzby I am done with the audioservice for this game. Thank you again for your time and your input!

**Comment by czyzby** [comment]
> So, I thought I can use that but seems like in my case it does not work because KtxAsync has a different CoroutineScope than the show method?

This works in the case you posted, because `measureTimeMillis` is _inside_ the coroutine. If you wrapped the content of `KtxAsync.launch` alone, it would work. E.g.

```kotlin
KtxAsync.launch {
  measureTimeMillis {
     assetRefs.joinAll()
     assetsLoaded()
  }
}
```
This would measure the asset loading and `assetsLoaded()` call alone.

However, if you wanted to measure the complete initiation time from the beginning of the `create` method call up to changing the screen, you cannot do this with a single `measureTimeMillis` block.

**Pull request merged**
